### ISSUE TITLE
Quicker开启后，鼠标、窗口移动卡顿

### ISSUE THREAD

**Issue by C21H21NO2S** [cuiliang/QuickPadCn#1796]
最新稳定版，win11，圆角 毛玻璃都关了，之前有过，取消毛玻璃问题解决，最近更新后又出现了。

**Comment by cuiliang** [comment]
winver 截图一下版本号。 
是qk只要开启，不管是不是显示了，移动其它窗口都会卡顿么？

**Comment by C21H21NO2S** [comment]
是的，开启qk后，不管有没有显示窗口，win11 里会卡顿。但在另外一台win10上却没有这问题。截图上传一直出错...

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022-‎09-‎22
操作系统版本	22621.674
体验	Windows Feature Experience Pack 1000.22634.1000.0

--- 
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎12/‎22
操作系统内部版本	19044.2130
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by C21H21NO2S** [comment]
> 是的，开启qk后，不管有没有显示窗口，win11 里会卡顿。但在另外一台win10上却没有这问题。截图上传一直出错...
> 
> 版本 Windows 11 专业版 版本 22H2 安装日期 ‎2022-‎09-‎22 操作系统版本 22621.674 体验 Windows Feature Experience Pack 1000.22634.1000.0
> 
> 版本 Windows 10 专业版 版本号 21H2 安装日期 ‎2021/‎12/‎22 操作系统内部版本 19044.2130 体验 Windows Feature Experience Pack 120.2212.4180.0

是的，开启qk后，不管有没有显示窗口，win11 里会卡顿。但在另外一台win10上却没有这问题。截图上传一直出错...

版本 Windows 11 专业版
版本 22H2
安装日期 ‎2022-‎09-‎22
操作系统版本 22621.674
体验 Windows Feature Experience Pack 1000.22634.1000.0

版本 Windows 10 专业版
版本号 21H2
安装日期 ‎2021/‎12/‎22
操作系统内部版本 19044.2130
体验 Windows Feature Experience Pack 120.2212.4180.0

**Comment by cuiliang** [comment]
我也是这个版本的win11，没有这个现象。
你的显卡和显示器是什么样的呢？ 试试更新或降级一下显卡驱动呢？

![image](https://user-images.githubusercontent.com/1972649/197310640-299ce67a-32f4-46eb-a93b-8465215ee3c7.png)

**Comment by C21H21NO2S** [comment]
> 我也是这个版本的win11，没有这个现象。 你的显卡和显示器是什么样的呢？ 试试更新或降级一下显卡驱动呢？
> 
> ![image](https://user-images.githubusercontent.com/1972649/197310640-299ce67a-32f4-46eb-a93b-8465215ee3c7.png)

win11的是1070，显示器是144hz的，晚点更新驱动再看看

**Comment by cuiliang** [comment]
不清楚这个会不会和Quicker所使用的WPF技术有关，WPF底层依赖DirectX，可能最高只支持60帧。 刚搜到一个 https://github.com/dotnet/wpf/issues/2294 
我这里没用过高刷的屏幕，所以也没法试验。 屏幕能设置成60刷新么？如果可以，可以观察下锁定60hz的情况下会不会好。

**Comment by cuiliang** [comment]
https://www.reddit.com/r/1Password/comments/j17ou6/when_you_have_high_refresh_rate_144hz_ui_lags_and/ 还有这里
里面有一个人给了一个方法可以试试：
Hello!

I found a method! I have an AOC 24G2U 144Hz monitor. When i installed it, the Windows UI lagged, like the Win 98. Today, i was experimenting with things, and i found, that if you have wallpapers in slideshow (or any live wallpaper third party app (Lively, WP Engine)), it lags the UI. I resetted everything in NVIDIA Control Panel, then right click on desktop, monitor-setup, advanced display settings, select your monitor, and here make it to 120Hz or 240Hz. Dont use 144Hz in you desktop, because for me, it causes stutter. And you cant divide 144 with 60 (basically all system animations run at 60FPS and you cant multiply 60 to 144 without losing frames...). Hope this helps!

**Comment by cuiliang** [comment]
另外，可以尝试这里的方法：
https://github.com/microsoft/PowerToys/issues/11810#issuecomment-877597128

**Comment by C21H21NO2S** [comment]
> 另外，可以尝试这里的方法： [microsoft/PowerToys#11810 (comment)](https://github.com/microsoft/PowerToys/issues/11810#issuecomment-877597128)

嗯嗯，谢谢，我晚点都试一试。
